stages:
  - build
  - test

tabou2-front:build:
  stage: build
  image: node:16.20.2
  only:
    refs:
      - develop
  script:
    - git submodule update --init --recursive
    - npm ci
    - npm run ext:build
  artifacts:
    paths :
      - $CI_PROJECT_DIR/dist/Tabou2.zip


tabou2-front:sonar-analysis:
  stage: test
  image: sonarsource/sonar-scanner-cli
  script:
    - >
      sonar-scanner
      -Dsonar.host.url=${SONAR_URL}
      -Dsonar.login=${SONAR_TOKEN}
      -Dsonar.projectKey=${SONAR_KEY}${CI_PROJECT_NAME}

